{"name": "Авторизаиця с недействительными учетными данными", "status": "passed", "steps": [{"name": "Открыть страницу авторизации", "status": "passed", "start": 1723396708352, "stop": 1723396709443}, {"name": "Ввести в форму авторизации недействительные учетные данные", "status": "passed", "start": 1723396709443, "stop": 1723396709606}, {"name": "Отображается ошибка - Invalid credentials. Please try again.", "status": "passed", "start": 1723396709606, "stop": 1723396709624}], "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1723396708351, "stop": 1723396709624, "uuid": "c0971741-fc3b-417b-84c3-9f1c07009c14", "historyId": "f5f8d27f1652eca3be76f09a33608fb2", "testCaseId": "04ca39b848a17d7ece226d3b14182604", "fullName": "tests.login_test#test_login_failure", "labels": [{"name": "story", "value": "Авторизации недействительные учетные данные"}, {"name": "severity", "value": "critical"}, {"name": "feature", "value": "Авторизаци"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "login_test"}, {"name": "host", "value": "WIN-0MTTCQFVLIA"}, {"name": "thread", "value": "14376-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.login_test"}]}